# ---CONSTANTS---

# Screen Config
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_BACKGROUND_COLOR = "black"

# Paddle Config
PADDLE_COLOR = "white"
PADDLE_HEIGHT = 5
PADDLE_WIDTH = 1
PADDLE_DISTANCE_TO_WALL = 50
PADDLE_Y_POSITION = 0
PADDLE_SHAPE = "square"
PADDLE_MOVE_DISTANCE = 20
PADDLE_SPEED = "fastest"
PADDLE_RESIZE_MODE = "user"
