# ---CONSTANTS---

# Screen Config
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_BACKGROUND_COLOR = "black"
SCREEN_REFRESH_TIME = 0.05

# Paddle Config
PADDLE_COLOR = "white"
PADDLE_HEIGHT = 5
PADDLE_WIDTH = 1
PADDLE_DISTANCE_TO_WALL = 50
PADDLE_Y_POSITION = 0
PADDLE_SHAPE = "square"
PADDLE_MOVE_DISTANCE = 20
PADDLE_SPEED = "fastest"
PADDLE_RESIZE_MODE = "user"

# Keys Config
LEFT_PADDLE_UP_KEY = "w"
LEFT_PADDLE_DOWN_KEY = "s"
RIGHT_PADDLE_UP_KEY = "Up"
RIGHT_PADDLE_DOWN_KEY = "Down"

# Ball Config
BALL_SHAPE = "circle"
BALL_TURTLE_SPEED = "fastest"
BALL_COLOR = "white"
BALL_MOVEMENT_SPACE = 10
BALL_INITIAL_HEADING = 45
BALL_BOUNCE_ANGLE = 270
BALL_WIDTH = 20
BALL_BOUNCING_Y_ERROR_SPACE = 7
BALL_BOUNCING_X_ERROR_SPACE = 20
BALL_BOUNCING_DISTANCE_TO_PADDLE = 50
BALL_INCREASE_SPEED_WHEN_TOUCH_PADDLE = 0.1

# Score Board Config
SCOREBOARD_SPEED = "fastest"
SCOREBOARD_COLOR = "white"
SCOREBOARD_X_DISTANCE_TO_CENTER = 50
SCOREBOARD_Y_DISTANCE_TO_TOP = 50
SCOREBOARD_TEXT_ALIGN = "center"
SCOREBOARD_TEXT_FONT = "Console"
SCOREBOARD_TEXT_SIZE = 24
SCOREBOARD_TEXT_STYLE = "bold"
